name: release
on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.30.2
      - uses: actions/setup-node@v4
        with:
          node-version: current
          registry-url: "https://registry.npmjs.org/"
      - run: pnpm install
      - run: pnpm build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
